### ISSUE TITLE
Error in running ros_reality_bridge.launch

### ISSUE THREAD

**Issue by ghost** [h2r/ros_reality_bridge#6]
Hello,
I am beginner.
I would like to implement this program on Baxter research robot.
However, when I attempt to run ros_reality_bridge.launch, some errors occur.

Traceback (most recent call last):
  File "/home/ueda/baxter_ws/src/ros_reality_bridge/src/unityNode.py", line 77, in <module>
    main()
  File "/home/ueda/baxter_ws/src/ros_reality_bridge/src/unityNode.py", line 72, in main
    pub_string = message_builder(link_dict)
  File "/home/ueda/baxter_ws/src/ros_reality_bridge/src/unityNode.py", line 18, in message_builder
    trans, rot = v
TypeError: 'NoneType' object is not iterable
[ros_reality_node-13] process has died [pid 10891, exit code 1, cmd /home/ueda/baxter_ws/src/ros_reality_bridge/src/unityNode.py __name:=ros_reality_node __log:=/home/ueda/.ros/log/670a05b6-e0b2-11e8-9f3a-3495db2e8964/ros_reality_node-13.log].
log file: /home/ueda/.ros/log/670a05b6-e0b2-11e8-9f3a-3495db2e8964/ros_reality_node-13*.log

Do you know what the problem is?

**Comment by ghost** [comment]
I'm sorry. 
This problem was solved.
